import { useRef, useState } from 'react';
import { Camera, ImagePlus, Trash2 } from 'lucide-react';
import { api } from '../utils/api';
import { useResource } from '../hooks/useAppData';
import { formatDate } from '../utils/data';
import { EmptyState, ErrorState, LoadingState, PageIntro } from './Home';

export default function ProgressPage() {
  const { data: rawPictures, loading, error, reload } = useResource(api.progress.list); const pictures = Array.isArray(rawPictures) ? rawPictures : [];
  const [file, setFile] = useState(null); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [uploading, setUploading] = useState(false); const [uploadError, setUploadError] = useState(''); const inputRef = useRef(null);
  const upload = async (event) => { event.preventDefault(); if (!file) return; setUploading(true); setUploadError(''); try { await api.progress.upload(file, date); setFile(null); if (inputRef.current) inputRef.current.value = ''; reload(); } catch (err) { setUploadError(err.message); } finally { setUploading(false); } };
  const remove = async (picture) => { if (!window.confirm('Delete this progress picture?')) return; try { await api.progress.remove(picture.id || picture._id); reload(); } catch (err) { window.alert(err.message); } };
  if (loading) return <div className="page-container"><PageIntro eyebrow="Progress" title="See your progress" /><LoadingState /></div>;
  if (error) return <div className="page-container"><PageIntro eyebrow="Progress" title="See your progress" /><ErrorState message={error} onRetry={reload} /></div>;
  return <div className="page-container"><PageIntro eyebrow="Progress" title="See your progress" description="Save regular snapshots and let the changes speak for themselves." />
    <section className="card mb-8 p-5 sm:p-6"><form onSubmit={upload} className="flex flex-col gap-4 sm:flex-row sm:items-end"><label className="field flex-1"><span>Progress picture</span><div className="relative flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border border-dashed border-white/[0.14] bg-[#0C0C0C] px-4 text-sm text-[#888] transition hover:border-[#7CFF5B]/50"><ImagePlus className="h-5 w-5 text-[#7CFF5B]" />{file ? <span className="truncate text-white">{file.name}</span> : 'Choose an image'}<input ref={inputRef} required type="file" accept="image/*" onChange={(e) => setFile(e.target.files?.[0] || null)} className="absolute inset-0 cursor-pointer opacity-0" /></div></label><label className="field sm:w-44"><span>Date</span><input required type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label><button disabled={!file || uploading} className="button-primary h-12 sm:w-auto">{uploading ? 'Uploading…' : 'Save picture'}</button></form>{uploadError && <p className="mt-3 text-sm text-[#FF8CAE]">{uploadError}</p>}</section>
    {pictures.length ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{[...pictures].sort((a, b) => new Date(a.date || a.createdAt) - new Date(b.date || b.createdAt)).map((picture) => { const src = picture.url || picture.imageUrl || picture.picture || picture.path; return <article key={picture.id || picture._id || src} className="group relative overflow-hidden rounded-2xl border border-white/[0.07] bg-[#111]"><img src={src} alt={`Progress from ${formatDate(picture.date || picture.createdAt)}`} className="aspect-[3/4] w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-x-0 bottom-0 flex items-center justify-between bg-gradient-to-t from-black/90 to-transparent px-3 pb-3 pt-10"><span className="text-xs font-medium text-white">{formatDate(picture.date || picture.createdAt)}</span><button onClick={() => remove(picture)} className="rounded-lg bg-black/40 p-2 text-[#FF9AB4] opacity-0 transition group-hover:opacity-100" aria-label="Delete picture"><Trash2 className="h-4 w-4" /></button></div></article>; })}</div> : <EmptyState title="Your progress story starts here" description="Upload your first picture to keep a visual record of your training." action={<button onClick={() => inputRef.current?.click()} className="button-secondary"><Camera className="h-4 w-4" /> Choose a picture</button>} />}
  </div>;
}

